[package]
name = "cachewarmer"
version = "0.1.0"
authors = ["Grzegorz Nosek <root@localdomain.pl>"]
edition = "2018"

[dependencies]
futures = "0.3"
reqwest = {version = "0.13.1", features = ["blocking"]}
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
